name: Telegram Bot notify

on:
  push:
    branches: [master]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Notify
        uses: ./.github/actions
        with:
          token: ${{ secrets.token }}